# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaces/chamada_dialog.ui'
#
# Created: Wed Mar 13 10:38:11 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(439, 632)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.alunosList = QtGui.QTreeWidget(Dialog)
        self.alunosList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.alunosList.setAutoFillBackground(True)
        self.alunosList.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.alunosList.setFrameShape(QtGui.QFrame.StyledPanel)
        self.alunosList.setFrameShadow(QtGui.QFrame.Sunken)
        self.alunosList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.alunosList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.alunosList.setAlternatingRowColors(True)
        self.alunosList.setIconSize(QtCore.QSize(32, 32))
        self.alunosList.setRootIsDecorated(False)
        self.alunosList.setUniformRowHeights(True)
        self.alunosList.setItemsExpandable(True)
        self.alunosList.setAnimated(True)
        self.alunosList.setAllColumnsShowFocus(True)
        self.alunosList.setWordWrap(False)
        self.alunosList.setHeaderHidden(False)
        self.alunosList.setExpandsOnDoubleClick(False)
        self.alunosList.setObjectName(_fromUtf8("alunosList"))
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        item_0 = QtGui.QTreeWidgetItem(self.alunosList)
        self.alunosList.header().setVisible(True)
        self.alunosList.header().setCascadingSectionResizes(False)
        self.alunosList.header().setDefaultSectionSize(100)
        self.alunosList.header().setHighlightSections(True)
        self.alunosList.header().setStretchLastSection(True)
        self.gridLayout.addWidget(self.alunosList, 1, 0, 1, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.turmaLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.turmaLabel.setFont(font)
        self.turmaLabel.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.turmaLabel.setObjectName(_fromUtf8("turmaLabel"))
        self.verticalLayout.addWidget(self.turmaLabel)
        self.aulaLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.aulaLabel.setFont(font)
        self.aulaLabel.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.aulaLabel.setObjectName(_fromUtf8("aulaLabel"))
        self.verticalLayout.addWidget(self.aulaLabel)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setEnabled(True)
        self.label_2.setMaximumSize(QtCore.QSize(80, 80))
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/rfid-icon_2.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.setSortingEnabled(True)
        self.alunosList.headerItem().setText(0, QtGui.QApplication.translate("Dialog", "Presença", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.headerItem().setText(1, QtGui.QApplication.translate("Dialog", "Nome", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.headerItem().setText(2, QtGui.QApplication.translate("Dialog", "Matrícula", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.alunosList.isSortingEnabled()
        self.alunosList.setSortingEnabled(False)
        self.alunosList.topLevelItem(0).setText(0, QtGui.QApplication.translate("Dialog", "Presente", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(0).setText(1, QtGui.QApplication.translate("Dialog", "Fulando da Silva Santos", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(0).setText(2, QtGui.QApplication.translate("Dialog", "matrícula bem grande aaabbbcccdddeee", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(1).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(2).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(3).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(4).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(5).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(6).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(7).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(8).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(9).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(10).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(11).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(12).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(13).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(14).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(15).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(16).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.topLevelItem(17).setText(1, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.alunosList.setSortingEnabled(__sortingEnabled)
        self.label.setText(QtGui.QApplication.translate("Dialog", "Aproxime o cartão do sensor.", None, QtGui.QApplication.UnicodeUTF8))
        self.turmaLabel.setText(QtGui.QApplication.translate("Dialog", "Turma: Tal Tal", None, QtGui.QApplication.UnicodeUTF8))
        self.aulaLabel.setText(QtGui.QApplication.translate("Dialog", "Aula: Tal Tal", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

